name: Deploy to Nest

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy personal site
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: hackclub.app
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/bnajns
            git switch main
            git pull
            npm ci || exit 1
            npm run build || exit 1
            npm run start || exit 1
